### ISSUE TITLE
Wrong useless assignment detection in reduce block

### ISSUE THREAD

**Issue by mamantoha** [crystal-ameba/ameba#142] opened 2020-03-29 14:27 UTC
Example of code:

```crystal
ary = [1, 2, 3]

ary.reduce(0) do |sum, el|
  sum += el
end
```

Ameba returns:

```
...
[W] Lint/UselessAssign: Useless assignment to variable `sum`
> sum += el
  ^
Finished in 627 microseconds
```

**Comment by Blacksmoke16** [comment] 2020-03-29 14:31
Technically it's correct since the proper syntax in `#reduce` is just `sum + el`.

**Comment by Sija** [comment] 2020-03-29 14:35
@Blacksmoke16 no, it's not since:

- it ain't about the return value from the block
- it doesn't have anything to do with _syntax_ and
- `sum += el` expands to `sum = sum + el` which is equivalent to what you've written

**Comment by Blacksmoke16** [comment] 2020-03-29 14:40
```cr
ary = [1, 2, 3]

ary.map do |el|
  v = 0

  v += el

  v
end
```

Works fine, so the issue is specific to `#reduce`.

> * `sum += el` expands to `sum = sum + el` which is equivalent to what you've written

This is _NOT_ equivalent to what I wrote.  `#reduce` is setup like `memo = yield memo, elem`.  `#reduce` just needs to return the new value that should be assigned to `memo`.  `sum += el` _IS_ useless since the assignment to `sum` is redundant.

**Comment by mamantoha** [comment] 2020-03-29 14:41
@Blacksmoke16 yes, you're right

**Comment by Sija** [comment] 2020-03-29 14:55
oh, it **is** correct after all since `sum` is a block variable. It has nothing to do with `reduce` or block return value anyway though.

**Closed** 2020-03-29 15:00 UTC
