### ISSUE TITLE
Error on macro expansion when building with Crystal 1.9.0

### ISSUE THREAD

**Issue by mrexox** [crystal-ameba/ameba#389] opened 2023-07-12 07:48 UTC
I have upgraded Crystal version to the new 1.9.0 and got this error ([logs](https://github.com/coverallsapp/coverage-reporter/actions/runs/5528903612/jobs/10086251679?pr=90)):
```
Building: ameba
Error target ameba failed to compile:
Showing last frame. Use --error-trace for full trace.

There was a problem expanding macro 'macro_139947943079200'

Code in /home/runner/work/_temp/crystal-1.9-true-undefined/share/crystal/src/yaml/serialization.cr:188:7

 188 | {% begin %}
       ^
Called macro defined in /home/runner/work/_temp/crystal-1.9-true-undefined/share/crystal/src/yaml/serialization.cr:188:7

 188 | {% begin %}

Which expanded to:

 > 69 |                   
 > 70 | 
 > 71 |                   __temp_722 =
                          ^
Error: type must be Ameba::Severity, not (Ameba::Severity | Nil)
```

I guess that ameba hasn't yet been tested against Crystal 1.9, so I report this issue. I'll be glad to provide any help from my side.

**Comment by Sija** [comment] 2023-07-12 10:49
It should be fixed in `master`.
Soon I'll release v1.5.0.

**Comment by Sija** [comment] 2023-07-13 00:26
Duplicate of #372

**Closed by Sija** 2023-07-13 00:26 UTC
