### ISSUE TITLE
postinstall ameba 1.4.3 on Crystal 1.9.2 failed with: Error: type must be Ameba::Severity, not (Ameba::Severity | Nil)

### ISSUE THREAD

**Issue by zw963** [crystal-ameba/ameba#395] opened 2023-07-28 17:49 UTC
```
 ╰─ $ shards update
Resolving dependencies
Fetching https://github.com/crystal-ameba/ameba.git
Installing ameba (1.4.3)
Postinstall of ameba: make bin && make run_file
Failed postinstall of ameba on make bin && make run_file:
shards build -Dpreview_mt
Dependencies are satisfied
Building: ameba
Error target ameba failed to compile:
Showing last frame. Use --error-trace for full trace.

There was a problem expanding macro 'macro_140220368106480'

Code in /home/zw963/Crystal/share/crystal/src/yaml/serialization.cr:188:7

 188 | {% begin %}
       ^
Called macro defined in /home/zw963/Crystal/share/crystal/src/yaml/serialization.cr:188:7

 188 | {% begin %}

Which expanded to:

 > 75 |                   
 > 76 | 
 > 77 |                   __temp_722 =
                          ^
Error: type must be Ameba::Severity, not (Ameba::Severity | Nil)

make: *** [Makefile:9: build] Error 1
```

**Comment by veelenga** [comment] 2023-07-28 19:37
Duplicate of #372
Should be fixed #373

**Closed by veelenga** 2023-07-28 19:37 UTC
