### ISSUE TITLE
Installation failing on windows CI

### ISSUE THREAD

**Issue by wout** [crystal-ameba/ameba#377] opened 2023-06-12 18:32 UTC
I'm getting the following error running the CI workflow of one of my shards on Windows:

```bash
Installing ameba (1.1.0)
Postinstall of ameba: make bin && make run_file
Failed postinstall of ameba on make bin && make run_file:
shards build -Dpreview_mt

Dependencies are satisfied

Building: ameba

mkdir -p ../../bin

cp ./bin/ameba ../../bin

mingw[32](https://github.com/wout/lucky_vite/actions/runs/5247111964/jobs/9476844690#step:4:33)-make: *** No rule to make target '&&'.  Stop.
Error: Process completed with exit code 1.
```

**Comment by Sija** [comment] 2023-06-12 18:58
Duplicate of #368

**Closed by Sija** 2023-06-12 18:58 UTC
Labels: windows
